help:
    @just --list --unsorted

# ----------------------------------------------------------------------

venv:
    uv sync --exact

test *args:
    uv run python -m pytest {{ args }}

fmt:
    ruff format
    ruff check --select I --fix

ipython:
    uv run --with ipython python -m IPython

# ----------------------------------------------------------------------

[group('run')]
update-places *args:
    uv run update_places.py {{ args }}

[group('run')]
fetch-venue-metadata *args:
    uv run fetch_venue_metadata.py {{ args }}
