help:
    @just --list --unsorted

# ----------------------------------------------------------------------

venv:
    uv sync --exact

test *args:
    uv run python -m pytest {{ args }}

fmt:
    ruff format
    ruff check --select I --fix

# ----------------------------------------------------------------------

[group('run')]
update-places *args:
    uv run update_places.py {{ args }}

[group('run')]
generate-place-ids *args:
    uv run generate_place_ids.py {{ args }}
